### ISSUE TITLE
change display orientation

### ISSUE THREAD

**Issue by visit1985** [pimoroni/st7036#2]
Hi, is there a way to change the display orientation of the dot3k? I'm not an electrical engeneer, but according to the [specs](https://www.newhavendisplay.com/app_notes/ST7036.pdf) the ST7036 has two pins to change the orientation (SHLC/SHLS ITO option pin), but I don't know, if they are controllable via GPIO. Any help would be highly appreciated.

**Comment by Gadgetoid** [comment]
I don't believe there is, some features of the ST7036 controller are simply not broken out or used on the EA DOG 163 display.
